# Workflow to build run unit tests

name: Build & run Unit Tests

on:
  pull_request:

jobs:
  build-and-test:
    name: Build & run Unit Tests

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.9' ]

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3

    - name: Build dcm2niix
      run: |
        # build from source: https://github.com/rordenlab/dcm2niix#build-from-source
        sudo apt-get install cmake pkg-config
        git clone https://github.com/rordenlab/dcm2niix.git --branch master --single-branch
        cd dcm2niix
        mkdir build && cd build
        cmake ..
        make install

    - name: Test dcm2niix install
      run: |
        dcm2niix -h

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Display installed pip packages
      run: |
        pip list

    - name: Setup flake8 annotations
      uses: rbialon/flake8-annotations@v1

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Unit Tests with pytest
      run: |
        pytest tests/