# Workflow to publish TotalSegmentator-AIDE MAP on GHCR

name: Build and package MAP

on:
  push:
    branches: ['24_publish_map']

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.10' ]

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Display installed pip packages
      run: |
        pip list

    - name: Initial packaging of MAP-init
      run: |
        monai-deploy package app --tag map-init -l DEBUG

    - name: Package 3rd-party software into MAP
      run: |
        docker build -t map app/

#    # TODO: add step to run the MAP using test data
#    - name: Test MAP end-to-end
#      run: |
#        monai-deploy run map input-test-data-in-repo/ output/