# Workflow to publish TotalSegmentator-AIDE MAP on GHCR

name: Build and package MAP

on:
  push:
    branches: ['minimal-map-gha']

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.10' ]

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Display installed pip packages
      run: |
        pip list

    - name: Package MAP & test MAP end-to-end
      run: |
        monai-deploy package app --tag map/init:temp -l DEBUG
        docker images
        docker build --build-arg INIT_CONTAINER=map/init:temp -t map/final:temp app
        docker images
        monai-deploy run map tests/data/rtstructwriter/dcm tests/data/output
        ls tests/data/output
        if test -f "tests/data/output/output-rt-struct.dcm"; then echo "Output RT Struct exists."; fi